### ISSUE TITLE
SimpleDocs parser requires empty line as EOF in JS files

### ISSUE THREAD

**Issue by Jemt** [Jemt/Fit.UI#35] opened 2018-07-17 14:27 UTC
The following exception is thrown when generating documentation, unless an empty line is found in the end of each JS file:

```
Unhandled Exception:
System.Xml.XmlException: The 'documentation' start tag on line 2 position 2 does not match the end tag of 'container'. Line 2760, position 3.
  at SimpleDocs.Parser.Parse (System.String xmlComments, System.Boolean includePrivate) [0x00099] in <555d6fe1509346ed93a3c5aeee8b59bd>:0
  at SimpleDocs.MainClass.Main (System.String[] args) [0x001f2] in <555d6fe1509346ed93a3c5aeee8b59bd>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.Xml.XmlException: The 'documentation' start tag on line 2 position 2 does not match the end tagof 'container'. Line 2760, position 3.
  at SimpleDocs.Parser.Parse (System.String xmlComments, System.Boolean includePrivate) [0x00099] in <555d6fe1509346ed93a3c5aeee8b59bd>:0
  at SimpleDocs.MainClass.Main (System.String[] args) [0x001f2] in <555d6fe1509346ed93a3c5aeee8b59bd>:0
```

To reproduce, simply remove the last empty line in e.g. Controls/Dialog/Dialog.js and execute
`cd build && ./Build`

**Comment by FlowIT-JIT** [comment] 2019-04-12 12:25
Turns out that the problem was actually caused by Merge shell script which concatenated files without line breaks in between. This could result in two files with content such as:

function test(){ /* logic */ }

and

/// <container ...>
/// </container>

to be concatenated like:

function test(){ /* logic */ } /// <container ...>
/// </container>

SimpleDocs would remove /// <container ...> ([leave it out](https://github.com/Jemt/SimpleDocs/blob/master/FileHandler.cs#L59)) since it is not considered documentation, resulting in a closing tag (</container>) with not starting tag, hence producing an invalid XML document.

**Closed** 2019-04-12 12:34 UTC
Labels: minor bug
